#!/bin/sh

#
# One-time startup script to configure the CLC
#
# chkconfig: - 95 50
# description: This script initializes and configures a CLC
# processname: eucalyptus-frontend-config
#

LOGFILE=/var/log/eucalyptus/frontend-config.log

case "$1" in
  start)
    plymouth --hide-splash
    /usr/local/sbin/eucalyptus-frontend-config 2>&1 | tee $LOGFILE
    plymouth --show-splash
    chkconfig eucalyptus-setup off
    ;;
  *)
    exit 0
    ;;
esac
