#!/usr/bin/python

import os
import subprocess
import urllib2
from urllib import urlencode

metadata_file = '/etc/silvereye-release'
checkin_url = 'http://tools.eucalyptus.com/list.php'

data = dict()

if not os.path.exists(metadata_file):
  p = subprocess.Popen([ 'rpm', '-q', '--qf', '%{VERSION}', 'eucalyptus' ],
                       stdout=subprocess.PIPE)
  data['version'] = p.communicate()[0]
  data['commit'] = 'unknown'
else:
  data.update([ x.strip().split('=') for x in open(metadata_file, 'r').readlines() if len(x) > 1 ])

try:
  txdata = urlencode(data)
  checkin_url += "?" + txdata
  txheaders = { 'User-agent' : 'Mozilla/4.0 (compatible; Silvereye 3; Linux)'}
  opener = urllib2.build_opener()
  req = urllib2.Request(checkin_url, None, txheaders)
  handle = opener.open(req, None, 5)
  response = handle.read()
  opener.close()
except:
  pass
