 
splash.lss

NOTE: It is recommended that you install and configure Node Controllers prior to installing and configuring your Frontend.

 -  To install CentOS 5 with Eucalyptus Node Controller, type: 0bnc <ENTER>07.

 -  To install CentOS 5 with Eucalyptus Frontend, type: 0bfrontend <ENTER>07.

 -  To install a single-server, Eucalyptus Cloud-in-a-box, type: 0bciab <ENTER>07.

 -  To install a minimal CentOS 5 without Eucalyptus, type: 0bminimal <ENTER>07.

 -  For text mode installations, append the word text, e.g., 0bnc text <ENTER>07.

 -  Use the function keys listed below for more information.

0f[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07
